tasks:
  - init: |
      # 安装 pyenv
      curl https://pyenv.run | bash
      # 配置 pyenv 环境变量
      echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
      echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
      echo 'eval "$(pyenv init -)"' >> ~/.bashrc
      # 重新加载 shell
      source ~/.bashrc
      # 安装 Python 3.7.5
      pyenv install 3.7.5
      # 设置 Python 3.7.5 为全局版本
      pyenv global 3.7.5
